-- Create the contacts table for storing contact form submissions
create table public.contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text,
    message text not null,
    source text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Create policy to allow anonymous inserts
create policy "Allow anonymous contact form submissions" on public.contacts
    for insert
    to anon
    with check (true);

-- Create policy to prevent anonymous reads
create policy "Prevent anonymous reads" on public.contacts
    for select
    to authenticated
    using (true);

-- Add helpful comment
comment on table public.contacts is 'Stores contact form submissions from the website'; 